apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  namespace: security-playground
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: default
      containers:
        - name: app
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          image: nginx:sha256@295c7be079025306c4f1d65997fcf7adb411c88f139ad1d34b537164aa060369
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100M
              memory: 100Mi
          ports:
            - containerPort: 80
